backend:
  name: github
  repo: missanakazz/research
  branch: main
  site_id: SEU-SITE-DO-NETLIFY.netlify.app # Coloque aqui o nome do site que o Netlify gerou para você

media_folder: "images"
public_folder: "/images"

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}

  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "date"}
